# Generated by Django 5.0 on 2023-12-17 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("codigo_produto", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("preco", models.FloatField()),
            ],
        ),
    ]
