# Generated by Django 5.0 on 2023-12-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("estoque", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
